repos:
    - repo: https://github.com/antonbabenko/pre-commit-terraform.git
      rev: v1.45.0
      hooks:
          - id: terraform_fmt

    - repo: git://github.com/pre-commit/pre-commit-hooks
      rev: v3.4.0
      hooks:
          - id: check-added-large-files
          - id: check-case-conflict
          - id: check-json
          - id: check-merge-conflict
          - id: check-yaml
          - id: debug-statements
          - id: detect-private-key
          - id: double-quote-string-fixer
          - id: forbid-new-submodules
          - id: trailing-whitespace
