-   repo: https://github.com/kintoandar/pre-commit.git
    sha: v0.0.2
    hooks:
    -   id: terraform_validate

-   repo: https://github.com/antonbabenko/pre-commit-terraform.git
    sha: v1.1.0
    hooks:
    -   id: terraform_fmt

-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: 46251c9523506b68419aefdf5ff6ff2fbc4506a4
    hooks:
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: debug-statements
    -   id: detect-private-key
    -   id: double-quote-string-fixer
    -   id: end-of-file-fixer
    -   id: forbid-new-submodules
    -   id: trailing-whitespace
